sudo: true
git:
  submodules: true
language: python
python:
  - "2.7"
before-install:
  - sudo apt-get install build-essential
install:
  - pip install -r requirements.txt
  - make DESTDIR=./travis install
  - make rpm
script:
  - make
notifications:
  email:
    on_success: never
    on_failure: never
