sudo: false
git:
  submodules: false
language: python
python:
  - "2.7"
install:
  - pip install flake8==2.4.1
script:
  - flake8 --show-source
notifications:
  email:
    on_success: never
    on_failure: always
